name: Windows Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: windows-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-latest
    defaults:
        run:
            shell: 'powershell'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install ninja-build tool (must be after Qt due PATH changes)
      uses: turtlesec-no/get-ninja@main

    - name: Make sure MSVC is found when Ninja generator is in use
      uses: ilammy/msvc-dev-cmd@v1
        
    - name: Install 7zip
      run: choco install 7zip.install
      
    - name: Install Mesa
      shell: cmd
      run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
          "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          mklink opengl32.dll "x64\opengl32.dll"
          mklink libglapi.dll "x64\libglapi.dll"
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.8.1'
        host: windows
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        dir: '${{github.workspace}}/qt'
        install-deps: 'true'
        modules: 'qtcharts qtpositioning'
        cache: true
    
    - name: Configure
      env:
        CMAKE_PREFIX_PATH: ${{env.QT_ROOT_DIR}}/lib/cmake
      run: >
        cmake -G Ninja
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DALP_ENABLE_POSITIONING=false
        -DALP_ENABLE_ASSERTS=ON
        -B ./build

    - name: Build
      run: cmake --build ./build --config Debug

    - name: List .exe files in ./build
      shell: pwsh
      run: |
        Write-Host "Searching for .exe files in ./build..."
        Get-ChildItem -Path "./build" -Filter "*.exe" -Recurse | ForEach-Object {
          Write-Host "Found: $($_.FullName)"
        }

    - name: Unittests on Windows
      env:
        MESA_GL_VERSION_OVERRIDE: 3.3
      run: |
        ./build/unittests_radix.exe
        ./build/unittests_nucleus.exe
        
